//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denemem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public Nullable<System.DateTime> ReservationStartDate { get; set; }
        public Nullable<System.DateTime> ReservationEndDate { get; set; }
        public Nullable<bool> ReservationStuation { get; set; }
        public int CarID { get; set; }
        public Nullable<int> CustomerSSN { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
